version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - eva-reg-db
    env_file:
      - ./envs/web
    volumes:
      - ./:/app/:z
    ports:
      - "8010:8010"

  eva-reg-db:
    image: postgres:13
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./envs/web
    ports:
      - "5432"

  requirements:
    image: python:3.8-buster
    profiles:
      - utils
    volumes:
      - ./:/app/:z

  tests-eva-reg:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    image: tests_eva_reg
    env_file:
      - ./envs/tests
    profiles:
      - testing
    depends_on:
      - eva-reg-test-db

  eva-reg-test-db:
    image: postgres:13
    container_name: eva_reg_test_postgres
    env_file:
      - ./envs/tests
    expose:
      - "5432"

  build-static:
    build:
      context: .
      dockerfile: ./docker/build-static/Dockerfile
    image: build-static-eva-reg
    env_file:
      - ./envs/web
    volumes:
      - ./:/app/:z
    profiles:
      - build-static
