headers = [
    "Evaluation ID",
    "Report ID",
    "gov_uk_link",
    "Evaluation title",
    "Short title for evaluation",
    "Process",
    "Impact",
    "Economic",
    "Other evaluation type (please state)",
    "Report title",
    "Report type",
    "Government departments",
    "Author(s)",
    "Evaluation summary",
    "Intervention start date (Month)",
    "Intervention start date (Year)",
    "Intervention end date (Month)",
    "Intervention end date (Year)",
    "Processes and standards",
    "Evaluation cost (£)",
    "Publication date (Month)",
    "Publication date (Year)",
    "Links to associated docments",
    "Event category",
    "Event start date (Month)",
    "Event start date (Year)",
    "Event end date (Month)",
    "Event end date (Year)",
    "Issue to be addressed",
    "Who is experiencing the issue",
    "Current practice",
    "Why the issue is important / why are improvements needed",
    "Who does it matter to",
    "What difference the intervention intends to make",
    "Studied population including location(s)",
    "Eligibility criteria",
    "Total number of people (or other unit) included in the evaluation",
    "Type of unit",
    "Intervention name",
    "Intervention brief description",
    "Intervention rationale",
    "Materials used",
    "Procedures used",
    "Who delivered the intervention",
    "How was the intervention delivered",
    "Where was the intervention delivered",
    "How often the intervention was delivered",
    "Tailoring",
    "How well it was delivered (fidelity)",
    "Resource requirements",
    "Geographical information",
    "Intervention costs (£)",
    "Referral / recruitment route",
    "Referral / recruitment schedule",
    "Process - Design",
    "Process - Method",
    "Process - Method sample size",
    "Process - Method sample size process",
    "Process - Description",
    "Process - Rationale for chosen methods",
    "Impact - Design",
    "Impact - Justification for design",
    "Impact - Features to reflect real-world implementation",
    "Impact - Description",
    "Impact - Equity",
    "Impact - Method sample size",
    "Impact - Method sample size process",
    "Impact - Assumptions",
    "Impact - Limitations of approach",
    "Economic - Methods",
    "Economic - Method sample size",
    "Economic - Method sample size process",
    "Economic - Costs included",
    "Economic - Benefits included",
    "Economic - Monetisation approach",
    "Economic - Evaluation design",
    "Other - Evaluation design",
    "Other - Summary of methods",
    "Process - Description of analysis",
    "Impact - Analysis framework",
    "Impact - Analysis basis",
    "Impact - Analysis set",
    "Impact - Primary effect size measure type",
    "Impact - Primary effect size measure",
    "Impact - Primary effect size measure interval",
    "Impact - Primary effect size measure description",
    "Impact - Interpretation type",
    "Impact - Sensitivity analysis",
    "Impact - Subgroup analysis",
    "Impact - Missing data handling",
    "Impact - Fidelity of report",
    "Impact - Description of analysis",
    "Economic - Description of analysis",
    "Other - Description of analysis",
    "Outcome title",
    "Primary or secondary outcome",
    "Direct or surrogate",
    "Measure type",
    "Description of measure",
    "Collection procedures",
    "Time point of intesest (Month)",
    "Time point of intesest (Year)",
    "Minimum practically important difference",
    "Relevance of outcome",
    "Other outcomes - Outcome name",
    "Other outcomes - Outcome measure type",
    "Other outcomes - Description of measure",
    "Other outcomes - Collection procedures and timing",
    "Process - Summary of findings",
    "Process - Findings",
    "Impact - Summary of findings",
    "Impact - Findings",
    "Economic - Summary of findings",
    "Economic - Findings",
    "Other - Summary of findings",
    "Other - Findings",
    "Ethics approval applied for",
    "Ethics committee approval",
    "Ethics committee details",
    "Ethical state of study given existing evidence base",
    "Risks to participants",
    "Risks to study team",
    "Participant involvement",
    "Participant consent (if no, why not)",
    "Participant information",
    "Participant payment (if yes, please ellaborate)",
    "Confidentiality and personal data",
    "Breaking confidentiality",
    "Other ethical information",
    "Name of standard or process",
    "Conformity",
    "Process and standards - Description",
]

data_row = [
    "1",
    "1",
    "https://www.gov.uk/government/publications/lstf-evaluation-visitor-travel-and-sustainable-transport",
    "Local Sustainable Transport Fund Evaluation",
    "LSTF evaluation",
    "N",
    "Y",
    "N",
    "N",
    "Local Sustainable Transport Fund Visitor Travel Case Study Final Report",
    "Main final report",
    "Department for Transport",
    "Cumbria Tourism",
    "This case study examines two LSTF programmes within three national parks which seek to address the issues arising from car-borne visitor travel through the implementation of sustainable transport schemes. The case study outlines the interventions that were implemented across the visitor areas and examines their potential impact on visitor travel behaviour.",
    "Jul",
    "2011",
    "Mar",
    "2015",
    "Information not identified within the report",
    "",
    "Dec",
    "2016",
    "",
    "Analysis",
    "Information not identified within the report",
    "2012",
    "Information not identified within the report",
    "2014",
    "issues arising from car-borne visitor travel",
    "conservation and recreation interests (e.g. wildlife trusts, National Trust, CTC/Sustrans) and local communities (e.g. parish councils, community groups, single-issue groups)",
    "Information not announced in the report",
    "The visitors to the parks also generate large amounts of car traffic that increasingly compromises the visitor experience and many of the special qualities that draw both residents and visitors to the three national parks in the first place. Air and water pollution levels rise; habitats and landscape character are threatened by vehicle encroachment; tranquillity is broken by traffic noise; and the wider impacts of transport emissions and their contribution to climate change are already being seen in changing ecosystems, migration patterns and other critical aspects of species and habitat survival.",
    "Department for Transport",
    "The purpose of the LSTF was to enable the delivery by local transport authorities of sustainable transport solutions that support economic growth while reducing carbon. These solutions would be geared to supporting jobs and business through effectively tackling the problems of congestion, improving the reliability and predictability of journey times, enabling economic investment and enhancing access to employment.",
    "Visitors. The case study outlines the interventions that were implemented across the visitor areas and examines their potential impact on visitor travel behaviour. Lessons are also drawn on the implementation and delivery of LSTF funded measures across the visitor areas studied",
    "Visitors to the area",
    "186",
    "people",
    "Local Sustainable Transport Fund",
    "The Local Sustainable Transport Fund1 (LSTF) supported investment in 96 local sustainable transport programmes between July 2011 and March 2015.",
    "• To support the local economy and facilitate economic growth, for example by reducing congestion, improving the reliability and predictability of journey times, or enhancing access to employment and other essential services; and • To reduce carbon emissions, for example by bringing about an increase in the volume and proportion of journeys made by low carbon sustainable modes including walking and cycling.",
    "support provided new or enhanced bus services, including the cost of operation, marketing as well as associated roadside infrastructure such as improvements to bus waiting facilities and information.",
    "Funded local transport schemes",
    "New Forest National Park Authority",
    "New Forest • An additional New Forest Tour route – the Blue Route – was introduced with LSTF funding support in 2013 and received a reduced amount of subsidy in 2014. All three New Forest Tour routes will operate commercially for the first time in 2015. • Development of a new responsive website for the New Forest Tour, together with full social media integration, online ticket sales and digital PR. • Enhancements to the New Forest Tour commentary, including GPS triggered commentary announcements. • Development of customer focussed collaterals, such as guide books, walks and cycle rides accessible from the New Forest Tour • Funding subsidy for the Beach Bus in 2013 and 2014, facilitating routing and frequency improvements to make the service more relevant to visitors. • Development of the Beach Bus brand identity, website and bus liveries. • 1 FTE Sustainable Transport Officer with responsibility for visitor bus services.",
    "New Forest National Park",
    "The Local Sustainable Transport Fund1 (LSTF) supported investment in 96 local sustainable transport programmes between July 2011 and March 2015.",
    "Information not identified in the report",
    "Information not identified in the report",
    "Information not identified in the report",
    "England",
    "£560m funding programme",
    "Information not identified in the report",
    "Information not identified in the report",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "Output or performance monitoring",
    "Tracking these indicators over time has made it possible to measure increased opportunities to get to and around project areas in a sustainable way, indicate which interventions have been most popular, and demonstrate the extent to which the expected LSTF outcome have materialised to date.",
    "information not easily identified within the report",
    "The project monitoring programme developed a series of indicators to track activity within the project areas. Indicators were selected on the basis of their relevance and availability and where possible are consistent across the project areas. Key indicators included: • Bus service passenger journey numbers, using data from bus ticket machines • Volume of cyclists, using fixed on and off road cycle counters • Volume of vehicles, using fixed traffic counters • Volume of rail passengers, using annual entries and exits from rail stations For the indicators listed above, the project monitoring allowed for a broad high level overview of activity within the project areas. For some of these indicators it isn’t possible to categorise the end user i.e. data may apply to a visitor, resident, business traveller etc. As such increases or decreases in activity cannot be robustly apportioned to LSTF interventions alone. That said, some project monitoring indicators related specifically to LSTF funded interventions which did allow apportionment, these included: • Number of meaningful engagements with the New Forest Travel concierge • Number of car club members, and miles • Beach Bus passenger journey numbers • Volume of participants in Skyride events Data were collected for the calendar years 2012, 2013 and 2014. However, not all indicators \nwere available in 2012 and therefore for some indicators meaningful analysis can only be \ndemonstrated between 2013 and 2014. ",
    "information not easily identified within the report",
    "information not easily identified within the report",
    "information not easily identified within the report",
    "Results have been extrapolated based on an assumption that the GoLakes Travel area contains approximately half of the total visitor numbers in the Lake District National Park area and as such are best estimates",
    "Due to the limitations of both time and budget, the indicators tracked do not cover the LSTF projects in their entirety, but instead were selective.",
    "",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "",
    "Information not identified within the report",
    "Information not identified within the report",
    "interviewed 300 businesses by telephone in the Lake District, South Downs and New Forest National Parks.",
    "Relative measure",
    "Numerical outcome",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "N/A",
    "N/A",
    "Reduced congestion",
    "Information not identified within the report",
    "Direct",
    "Continuous",
    "average daily traffic counts",
    "LSTF Visitor Travel Case Study Project Monitoring 2014",
    "Information not identified within the report",
    "2014",
    "Information not identified within the report",
    "Information not identified within the report",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "The Business Survey data showed creating links with local stakeholders and businesses to help promote and increase sustainable travel was a valuable technique employed by all three parks.",
    "Visitor Bus Services: The overall trend for visitor bus journeys in LSTF areas increased by 3.7% between 2012 and 2014 (555,715 journeys in 2012 and 576,068 journeys in 2014). Rates of increase have been mixed, with the largest observed increase to service levels nearly three times greater than at baseline (from 860 journeys in 2012 to 2,375 journeys in 2014) and the greatest decrease in service at -9.4% (from 89,141 journeys in 2012 to 80,763 journeys in 2014). • Cycling: Significant growth in the South Downs, with an average 93% increase between 2012 and 2014 at cycle counter locations (2,326 counts in 2012 and 4,485 counts in 2014), compared to a 24% growth in the New Forest between 2012 and 2014 (395 counts in 2012 and 491 counts in 2014). The Lake District demonstrated a 30.7% increase in the number of cycles carried on the Windermere Bike Boat between 2013 and 2014 (1,164 cycles in 2013 and 1,521 cycles in 2014). • Pay-as-you-drive Cars: This Lake District only initiative experienced challenges and after a positive 2013, popularity declined in 2014 (a 38% decrease overall from 9,463 miles in 2012 to 5,851 miles in 2014). • Hubs and Parking: The number of train passengers accessing the parks via the rail network, overall increased by 2.8% (station entries and exits 19.81 million in 2012 and 20.37 million in 2014), ranging from a decrease of -1.8% in the New Forest (station entries and exits 2.41 million in 2012 to 2.37 million in 2014) and increase of 5.7% in the Lake District (station entries and exits 1.04 million in 2012 to 1.10 million in 2014). Slight overall increases in vehicle traffic were evidenced over the project period, but are likely to reflect wider economic and social activity rather than a consequence of the LSTF interventions.",
    "N/A",
    "N/A",
    "N/A",
    "N/A",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "N",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "Information not identified within the report",
    "",
    "",
    "",
]
