name: Check code

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'develop'
      - 'pentest'
      - 'sandbox'
      - 'staging'

jobs:
  check_web:
    name: Check Python

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        pip install -r requirements-dev.lock

    - name: Run Python Code Checks
      run: |
        make check-python-code

    - uses: actions/checkout@v2
    - name: Slack Notification
      continue-on-error: true
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
        SLACK_TITLE: '${{ github.ref_name }} CodeCheck ${{ job.status }} :warning:'
        SLACK_USERNAME: ${{ github.actor }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'


  check_node:
    name: Check Node

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Run Node Code Checks
      run: |
        make check-node-code

    - uses: actions/checkout@v2
    - name: Slack Notification
      continue-on-error: true
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
        SLACK_TITLE: '${{ github.ref_name }} CodeCheck ${{ job.status }} :warning:'
        SLACK_USERNAME: ${{ github.actor }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'

  run_tests:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Tests
      run: |
        make test

    - uses: actions/checkout@v2
    - name: Slack Notification
      continue-on-error: true
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
        SLACK_TITLE: '${{ github.ref_name }} CodeCheck ${{ job.status }} :warning:'
        SLACK_USERNAME: ${{ github.actor }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'


  check_migrations:
    name: Check Migrations

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          docker-compose build web
          docker-compose run web python manage.py makemigrations --check

      - uses: actions/checkout@v2
      - name: Slack Notification
        continue-on-error: true
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
          SLACK_TITLE: '${{ github.ref_name }} CodeCheck ${{ job.status }} :warning:'
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
